// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Messages struct {
	Message              []*Message `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetMessage() []*Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type GetMessagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

type GetMessagesResponse struct {
	Messages             *Messages `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() *Messages {
	if m != nil {
		return m.Messages
	}
	return nil
}

type FindMessageByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMessageByIdRequest) Reset()         { *m = FindMessageByIdRequest{} }
func (m *FindMessageByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindMessageByIdRequest) ProtoMessage()    {}
func (*FindMessageByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *FindMessageByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMessageByIdRequest.Unmarshal(m, b)
}
func (m *FindMessageByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMessageByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindMessageByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMessageByIdRequest.Merge(m, src)
}
func (m *FindMessageByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindMessageByIdRequest.Size(m)
}
func (m *FindMessageByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMessageByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMessageByIdRequest proto.InternalMessageInfo

func (m *FindMessageByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindMessageByIdResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMessageByIdResponse) Reset()         { *m = FindMessageByIdResponse{} }
func (m *FindMessageByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindMessageByIdResponse) ProtoMessage()    {}
func (*FindMessageByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *FindMessageByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMessageByIdResponse.Unmarshal(m, b)
}
func (m *FindMessageByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMessageByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindMessageByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMessageByIdResponse.Merge(m, src)
}
func (m *FindMessageByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindMessageByIdResponse.Size(m)
}
func (m *FindMessageByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMessageByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMessageByIdResponse proto.InternalMessageInfo

func (m *FindMessageByIdResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type CreateMessageRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (m *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(m, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CreateMessageResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageResponse) Reset()         { *m = CreateMessageResponse{} }
func (m *CreateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMessageResponse) ProtoMessage()    {}
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *CreateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageResponse.Unmarshal(m, b)
}
func (m *CreateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageResponse.Marshal(b, m, deterministic)
}
func (m *CreateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageResponse.Merge(m, src)
}
func (m *CreateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMessageResponse.Size(m)
}
func (m *CreateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageResponse proto.InternalMessageInfo

func (m *CreateMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UpdateMessageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMessageRequest) Reset()         { *m = UpdateMessageRequest{} }
func (m *UpdateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageRequest) ProtoMessage()    {}
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *UpdateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageRequest.Unmarshal(m, b)
}
func (m *UpdateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageRequest.Merge(m, src)
}
func (m *UpdateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageRequest.Size(m)
}
func (m *UpdateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageRequest proto.InternalMessageInfo

func (m *UpdateMessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UpdateMessageResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMessageResponse) Reset()         { *m = UpdateMessageResponse{} }
func (m *UpdateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageResponse) ProtoMessage()    {}
func (*UpdateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *UpdateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageResponse.Unmarshal(m, b)
}
func (m *UpdateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageResponse.Merge(m, src)
}
func (m *UpdateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageResponse.Size(m)
}
func (m *UpdateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageResponse proto.InternalMessageInfo

func (m *UpdateMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageRequest) Reset()         { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()    {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *DeleteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageRequest.Unmarshal(m, b)
}
func (m *DeleteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageRequest.Merge(m, src)
}
func (m *DeleteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageRequest.Size(m)
}
func (m *DeleteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageRequest proto.InternalMessageInfo

func (m *DeleteMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DeleteMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageResponse) Reset()         { *m = DeleteMessageResponse{} }
func (m *DeleteMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageResponse) ProtoMessage()    {}
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *DeleteMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageResponse.Unmarshal(m, b)
}
func (m *DeleteMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageResponse.Merge(m, src)
}
func (m *DeleteMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageResponse.Size(m)
}
func (m *DeleteMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterType((*Messages)(nil), "grpc.Messages")
	proto.RegisterType((*GetMessagesRequest)(nil), "grpc.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "grpc.GetMessagesResponse")
	proto.RegisterType((*FindMessageByIdRequest)(nil), "grpc.FindMessageByIdRequest")
	proto.RegisterType((*FindMessageByIdResponse)(nil), "grpc.FindMessageByIdResponse")
	proto.RegisterType((*CreateMessageRequest)(nil), "grpc.CreateMessageRequest")
	proto.RegisterType((*CreateMessageResponse)(nil), "grpc.CreateMessageResponse")
	proto.RegisterType((*UpdateMessageRequest)(nil), "grpc.UpdateMessageRequest")
	proto.RegisterType((*UpdateMessageResponse)(nil), "grpc.UpdateMessageResponse")
	proto.RegisterType((*DeleteMessageRequest)(nil), "grpc.DeleteMessageRequest")
	proto.RegisterType((*DeleteMessageResponse)(nil), "grpc.DeleteMessageResponse")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdd, 0x4e, 0xc2, 0x40,
	0x10, 0x85, 0x69, 0x21, 0xfc, 0x0c, 0x82, 0xc9, 0x58, 0xa0, 0x56, 0x4c, 0xc8, 0xde, 0x48, 0xbc,
	0xe0, 0x02, 0x5e, 0x00, 0x11, 0x35, 0x18, 0x4d, 0x4c, 0x13, 0x1f, 0x00, 0xdd, 0x09, 0x21, 0x51,
	0x5a, 0xbb, 0x25, 0xd1, 0x57, 0xf0, 0xa9, 0x8d, 0xdd, 0x5d, 0xa0, 0xed, 0x62, 0x42, 0xbc, 0x83,
	0x39, 0xbb, 0xdf, 0x9c, 0x9d, 0x33, 0x29, 0x34, 0xde, 0x49, 0x88, 0xf9, 0x82, 0x06, 0x61, 0x14,
	0xc4, 0x01, 0x96, 0x16, 0x51, 0xf8, 0xca, 0x6e, 0xa0, 0xf2, 0x28, 0xcb, 0xd8, 0x04, 0x7b, 0xc9,
	0x5d, 0xab, 0x67, 0xf5, 0x6b, 0xbe, 0xbd, 0xe4, 0xd8, 0x86, 0xf2, 0x5a, 0x50, 0x34, 0xe3, 0xae,
	0x9d, 0xd4, 0xd4, 0x3f, 0x44, 0x28, 0xc5, 0xf4, 0x19, 0xbb, 0xc5, 0xa4, 0x9a, 0xfc, 0x66, 0x23,
	0xa8, 0x2a, 0x8c, 0xc0, 0x0b, 0xa8, 0xa8, 0x4e, 0xae, 0xd5, 0x2b, 0xf6, 0xeb, 0xc3, 0xc6, 0xe0,
	0xb7, 0xd5, 0x40, 0x1d, 0xf0, 0xb5, 0xca, 0x1c, 0xc0, 0x3b, 0x8a, 0xf5, 0x3d, 0x9f, 0x3e, 0xd6,
	0x24, 0x62, 0x76, 0x05, 0x27, 0xa9, 0xaa, 0x08, 0x83, 0x95, 0x20, 0xbc, 0x84, 0xaa, 0xba, 0x27,
	0x12, 0x8f, 0xf5, 0x61, 0x33, 0x85, 0x15, 0xfe, 0x46, 0x67, 0x7d, 0x68, 0xdf, 0x2e, 0x57, 0x5c,
	0x29, 0x93, 0xaf, 0x19, 0x57, 0xf0, 0xec, 0x1b, 0xd9, 0x04, 0x3a, 0xb9, 0x93, 0xaa, 0x61, 0xea,
	0x19, 0xd6, 0x1f, 0xcf, 0x98, 0x80, 0x73, 0x1d, 0xd1, 0x3c, 0x26, 0xad, 0xa8, 0x5e, 0xdb, 0xf9,
	0x59, 0xc6, 0xf9, 0xd9, 0x3b, 0xf3, 0x1b, 0x43, 0x2b, 0xc3, 0x38, 0xd4, 0x85, 0x0f, 0xce, 0x73,
	0xc8, 0xf3, 0x2e, 0xfe, 0x93, 0xea, 0x18, 0x5a, 0x19, 0xe6, 0xa1, 0xae, 0x1e, 0xc0, 0x99, 0xd2,
	0x1b, 0xe5, 0x5c, 0x75, 0xa1, 0xa6, 0x8e, 0x6c, 0xc6, 0xb3, 0x2d, 0xec, 0xf3, 0xc8, 0x3a, 0xd0,
	0xca, 0xd0, 0xa4, 0x9f, 0xe1, 0x77, 0x11, 0x8e, 0x74, 0x86, 0xc1, 0x3c, 0xe2, 0x38, 0x85, 0xfa,
	0xce, 0x12, 0xa1, 0x2b, 0xed, 0xe5, 0xb7, 0xcd, 0x3b, 0x35, 0x28, 0x12, 0xca, 0x0a, 0xf8, 0x04,
	0xc7, 0x99, 0xed, 0xc0, 0xae, 0x3c, 0x6f, 0x5e, 0x2f, 0xef, 0x7c, 0x8f, 0xba, 0x21, 0xde, 0x43,
	0x23, 0x95, 0x33, 0x7a, 0xf2, 0x86, 0x69, 0x81, 0xbc, 0x33, 0xa3, 0xb6, 0xcb, 0x4a, 0xa5, 0xa3,
	0x59, 0xa6, 0x35, 0xd0, 0x2c, 0x63, 0x9c, 0x92, 0x95, 0x9a, 0xac, 0x66, 0x99, 0xc2, 0xd3, 0x2c,
	0x63, 0x14, 0xac, 0xf0, 0x52, 0x4e, 0xbe, 0x2f, 0xa3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x48, 0x1f, 0x6b, 0x70, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessageBoardClient is the client API for MessageBoard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageBoardClient interface {
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	FindMessageById(ctx context.Context, in *FindMessageByIdRequest, opts ...grpc.CallOption) (*FindMessageByIdResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
}

type messageBoardClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBoardClient(cc grpc.ClientConnInterface) MessageBoardClient {
	return &messageBoardClient{cc}
}

func (c *messageBoardClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/grpc.MessageBoard/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) FindMessageById(ctx context.Context, in *FindMessageByIdRequest, opts ...grpc.CallOption) (*FindMessageByIdResponse, error) {
	out := new(FindMessageByIdResponse)
	err := c.cc.Invoke(ctx, "/grpc.MessageBoard/FindMessageById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, "/grpc.MessageBoard/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	out := new(UpdateMessageResponse)
	err := c.cc.Invoke(ctx, "/grpc.MessageBoard/UpdateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, "/grpc.MessageBoard/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBoardServer is the server API for MessageBoard service.
type MessageBoardServer interface {
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	FindMessageById(context.Context, *FindMessageByIdRequest) (*FindMessageByIdResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	UpdateMessage(context.Context, *UpdateMessageRequest) (*UpdateMessageResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
}

// UnimplementedMessageBoardServer can be embedded to have forward compatible implementations.
type UnimplementedMessageBoardServer struct {
}

func (*UnimplementedMessageBoardServer) GetMessages(ctx context.Context, req *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (*UnimplementedMessageBoardServer) FindMessageById(ctx context.Context, req *FindMessageByIdRequest) (*FindMessageByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMessageById not implemented")
}
func (*UnimplementedMessageBoardServer) CreateMessage(ctx context.Context, req *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (*UnimplementedMessageBoardServer) UpdateMessage(ctx context.Context, req *UpdateMessageRequest) (*UpdateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (*UnimplementedMessageBoardServer) DeleteMessage(ctx context.Context, req *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}

func RegisterMessageBoardServer(s *grpc.Server, srv MessageBoardServer) {
	s.RegisterService(&_MessageBoard_serviceDesc, srv)
}

func _MessageBoard_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MessageBoard/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_FindMessageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).FindMessageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MessageBoard/FindMessageById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).FindMessageById(ctx, req.(*FindMessageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MessageBoard/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MessageBoard/UpdateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MessageBoard/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageBoard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MessageBoard",
	HandlerType: (*MessageBoardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _MessageBoard_GetMessages_Handler,
		},
		{
			MethodName: "FindMessageById",
			Handler:    _MessageBoard_FindMessageById_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _MessageBoard_CreateMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _MessageBoard_UpdateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MessageBoard_DeleteMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
